packages = ["python-dotenv","pandas","requests","markdown","pygenaiapi"]
[[fetch]]
from = "./pyscripts/"
files = ["main.py","KibaliValues.csv","KibaliKeyIssues.csv"]
[[fetch]]
from = "./"
files = [".env"]
